### ISSUE TITLE
Getting Network Error during navigation

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/resources-ressources#358] opened 2022-12-19 21:28 UTC
**Describe the bug**
During the process of redeploying in AWS, if users navigate the site during the build, they might encounter an error.

**To Reproduce**
1. Go to AWS Amplify and redeploy
2. Navigate the site, clicking on resources while the build is ongoing
3. See error

**Screenshots**
<img width="1776" alt="Screenshot 2022-12-19 at 4 10 43 PM" src="https://user-images.githubusercontent.com/38330843/208527477-67ff8e6a-4931-4efb-abfc-7ff5eef13ad9.png">

**Comment by anikbrazeau** [comment] 2022-12-20 13:39
Possibly related to #305

**Comment by daine** [comment] 2023-01-16 18:47
Jan 16 update:

@anikbrazeau #305 I updated 305 to make it clear it had nothing to do with redeployments, and updated the title of this ticket to focus on the error as well. I think it's rare the errors are caused by redeployment, but rather by something in the code itself 😅

I redeployed today but didn't get this Network Error message. I've refreshed the site on Provision, Build and Deploy stages.

**Comment by ClementineHahn** [comment] 2023-04-17 20:57
Unable to reproduce error + winding down of service therefore closing this issue without full resolution

**Closed by ClementineHahn** 2023-04-17 20:57 UTC
Labels: BUG, CONTENTFUL
